# Generated by Django 2.1 on 2019-10-20 19:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('act', models.TextField()),
                ('act_time', models.DateTimeField(default=datetime.datetime(2019, 10, 20, 19, 32, 42, 764459))),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acting', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciving', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
