# Generated by Django 2.1 on 2019-10-20 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0002_auto_20191020_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 19, 46, 28, 547626)),
        ),
    ]
