# Generated by Django 2.1 on 2019-10-26 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0004_auto_20191023_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 19, 30, 29, 397367)),
        ),
    ]
