# Generated by Django 2.1 on 2019-11-02 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_activity', '0005_auto_20191026_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='act',
            name='act_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 2, 19, 27, 39, 353218)),
        ),
    ]
