# Generated by Django 2.1 on 2019-10-09 17:40

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('comment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('comment_date', models.TimeField(default=datetime.datetime(2019, 10, 9, 17, 40, 35, 766776, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_pic', models.ImageField(upload_to='posts')),
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('post_date', models.TimeField(default=datetime.datetime(2019, 10, 9, 17, 40, 35, 764778, tzinfo=utc))),
                ('likes', models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
