# Generated by Django 2.1 on 2019-09-28 18:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.TimeField(default=datetime.datetime(2019, 9, 28, 18, 11, 28, 217742, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.TimeField(default=datetime.datetime(2019, 9, 28, 18, 11, 28, 215743, tzinfo=utc)),
        ),
    ]
