# Generated by Django 2.1 on 2019-10-09 19:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20191009_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.TimeField(default=datetime.datetime(2019, 10, 9, 19, 32, 25, 925705, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.TimeField(default=datetime.datetime(2019, 10, 9, 19, 32, 25, 923706, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
