# Generated by Django 2.1 on 2019-10-13 00:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20191012_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.TimeField(default=datetime.datetime(2019, 10, 13, 0, 49, 19, 954268, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.TimeField(default=datetime.datetime(2019, 10, 13, 0, 49, 19, 952270, tzinfo=utc)),
        ),
    ]
