# Generated by Django 2.1 on 2019-10-13 01:06

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_auto_20191012_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.TimeField(default=datetime.datetime(2019, 10, 13, 1, 6, 8, 267171, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.TimeField(default=datetime.datetime(2019, 10, 13, 1, 6, 8, 265172, tzinfo=utc)),
        ),
    ]
