# Generated by Django 2.1 on 2019-10-20 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_auto_20191020_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 19, 32, 42, 760461)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 19, 32, 42, 758463)),
        ),
    ]
