# Generated by Django 2.1 on 2019-10-26 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_auto_20191023_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 19, 30, 29, 391370)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 19, 30, 29, 387373)),
        ),
    ]
